version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: pp_sedimentacion
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sedimentacion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bairon_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sedimentacion"]
      interval: 10s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
    driver: local

networks:
  bairon_network:
    external: true



